---
ubuntu_hardening:
  system_access: "System Access"
  password_section:
    password_expiry_warning:
      name: 'PasswordExpiryWarning'
      pattern: '^.*PASS_WARN_AGE.*$'
      value: 14
    maximum_password_age:
      name: 'PASS_MAX_DAYS'
      value: 90
    minimum_password_age:
      name: 'PASS_MIN_DAYS'
      value: 1
    minimum_password_length:
      name: 'PASS_MIN_LEN'
      value: 8
    password_complexity:
      name: 'password_complexity'
      value: 'password requisite pam_cracklib.so try_first_pass retry=3 minlen=8 dcredit=-1 ucredit=-1 ocredit=-1 lcredit=-1'
    clear_text_password:
      name: 'CLEAR_PASS_ENABLE'
      value: no
  account_lockout_section:
    lockout_bad_count:
      name: 'LOGIN_RETRIES'
      value: 5
    lockout_duration:
      name: 'LOGIN_TIMEOUT'
      value: 1800
    reset_lockout_count:
      name: 'HOME_MODE'
      value: 0750
