---
- hosts: "{{ target_hosts }}"
  gather_facts: no
  become: no
  vars_files: vars.yml
  tasks:
  #- name: Update list Packages
  #  apt:
  #    update_cache: yes
  #  when: ansible_os_family != 'Debian' or ansible_os_family != 'Ubuntu'

  - name: Install Curl
    apt:
      name: curl
      state: present

  - name: Install agent wazuh
    shell: curl -so wazuh-agent.deb https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.4.1-1_amd64.deb && sudo WAZUH_MANAGER='siem.emergya.com' WAZUH_AGENT_GROUP='{{ grupo }}' WAZUH_AGENT_NAME='{{ login }}'  dpkg -i ./wazuh-agent.deb

  - name: Add Agent in Wazuh client
    shell: echo {{ key_agent_base64 }} | base64 -d > /var/ossec/etc/client.keys

  - name: Restart Wazuh agent
    shell: systemctl restart wazuh-agent

  - name: Delete file wazuh-agent.deb
    shell: rm -rf wazuh-agent.deb

