---
- name: Instalar POSTMAN en Ubuntu
  hosts: '{{ target_hosts }}'
  become: true

  tasks:
    - name: Actualizar repositorios
      apt:
        update_cache: yes
      become: true

    - name: Instalar dependencias
      apt:
        name: 
          - libgtk2.0-0
          - libx11-xcb1
          - libxtst6
          - libgconf-2-4
          - libnss3
          - libasound2
          - libcanberra-gtk-module
        state: present
      become: true

    - name: Descargar archivo POSTMAN
      get_url:
        url: "https://dl.pstmn.io/download/latest/linux64"
        dest: /tmp/postman.tar.gz

    - name: Extraer archivo POSTMAN
      unarchive:
        src: /tmp/postman.tar.gz
        dest: /opt
        remote_src: yes
        creates: /opt/Postman

    - name: Crear enlace simbólico
      file:
        src: /opt/Postman/Postman
        dest: /usr/local/bin/postman
        state: link

    #- name: Agregar icono al menú
    #  copy:
    #    src: /opt/Postman/app/resources/app/assets/icon.png
    #    dest: /usr/share/icons/hicolor/256x256/apps/postman.png

    - name: Crear entrada de menú
      copy:
        content: |
          [Desktop Entry]
          Version=1.0
          Type=Application
          Name=Postman
          Icon=/usr/share/icons/hicolor/256x256/apps/postman.png
          Exec=/opt/Postman/Postman
          Categories=Development;
        dest: /usr/share/applications/postman.desktop
